web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./:/usr/share/nginx/html
        - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
        - mysql
php:
    build: .
    volumes:
        - ./:/usr/share/nginx/html
    links:
        - mysql
mysql:
    image: mysql:5.7
    ports:
        - "33061:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=laradock
        - MYSQL_USER=laradock
        - MYSQL_PASSWORD=secret
